import java.io.*;

public class Exception4 {

    public static void main(String[] args) {
    //    try{ 
    //      int x=0;
    //     int y=10;
    //     int z=y/x;
    //     System.out.println(z);
    // }
    // catch(final IOException e){
    //    System.out.println(e.getMessage());
    //    //throw new RuntimeException("operation failed" e)
    // }
    // try{
    //     int []a =new {9,5,8};
    //     int value = 9;
    //     throw 
    // }catch(ArrayIndexOutOfBoundsException e){
    //     System.out.println("the array is out of bound");
    // }
    
    
}
}
